{% set version = "0.27.3" %}

package:
  name: exiv2
  version: {{ version }}

source:
  url: https://github.com/Exiv2/exiv2/archive/v{{ version }}.tar.gz
  sha256: 6398bc743c32b85b2cb2a604273b8c90aa4eb0fd7c1700bf66cbb2712b4f00c1

build:
  number: 3
  run_exports:
    # https://abi-laboratory.pro/index.php?view=timeline&l=exiv2
    - {{ pin_subpackage('exiv2', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - expat
    - zlib
    - libiconv
    - gettext  # [osx]

test:
  commands:
    - exiv2 -h
    - test -f $PREFIX/lib/libexiv2${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_BIN%\\exiv2.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\exiv2.lib exit 1  # [win]

about:
  home: https://www.exiv2.org/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Exiv2 is a Cross-platform C++ library and a command line utility to manage image metadata
  description: |
    Exiv2 is a Cross-platform C++ library and a command line utility to manage image metadata. 
    It provides fast and easy read and write access to the Exif, IPTC and XMP metadata and the 
    ICC Profile embedded within digital images in various formats. Exiv2 is available as free 
    software and is used in many projects including KDE and Gnome Desktops as well as many 
    applications including GIMP, darktable, shotwell, GwenView and Luminance HDR. 
  doc_url: https://www.exiv2.org/manpage.html
  dev_url: https://github.com/Exiv2/exiv2

extra:
  recipe-maintainers:
    - gillins
    - ocefpaf
    - SrNetoChan
    - ceholden
